# Generated by Django 5.2.16 on 2026-08-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
    ]
